site_name: WQH的个人网站
site_url: https://amadeuscx.github.io/website/
site_author: WQH
site_description: WQH的个人网站


theme:
  name: material

  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.expand

  language: zh
  copyright: Copyright &copy; 2022 WQH


nav:
  - 笔记:
    - note/index.md
    - tools:
      - Makefile: note/Makefile/Makefile.md
  - 博客:
    - blog/index.md
  - 其他:
    - misc/index.md
