site_name: WQH的个人网站
site_url: https://amadeuscx.github.io/website/
site_author: WQH
site_description: WQH的个人网站


theme:
  name: material
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: 切换暗色
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换亮色
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.expand
  language: zh


copyright: Copyright &copy; 2022 WQH


nav:
  - 笔记:
    - note/index.md
    - tools:
      - Makefile: note/Makefile/Makefile.md
  - 博客:
    - blog/index.md
  - 其他:
    - misc/index.md



markdown_extensions:
  - pymdownx.arithmatex: # latex 支持
    generic: true

extra_javascript:
  # latex 公式 js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
